version: "3.9"
services:
  web:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./resume.json:/app/resume.json:ro
    depends_on:
      - mongo

  # New: dev mode
  web-dev:
    build: ./app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./app:/app # mount code
      - /app/node_modules # prevent overwriting node_modules with empty host dir
      - ./resume.json:/app/resume.json:ro
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
